# yaml-language-server: $schema=../schema.json
tokens:
  - addressOrDenom: "0x88C916cec7c70b222cB9CB774d20444CE3ce6a68"
    chainName: holesky
    collateralAddressOrDenom: "0x5899C38154D4fa25661C6026CbE8305E0d9AEDfE"
    connections:
      - token: ethereum|lumiatestnet|0x4a266c8fa92Be2Bab5E30b99Df84f6EC06CAD8e1
    decimals: 18
    name: Lumia Liquid Autocompounding Pirex Ether
    standard: EvmHypCollateral
    symbol: llapxETH
  - addressOrDenom: "0x4a266c8fa92Be2Bab5E30b99Df84f6EC06CAD8e1"
    chainName: lumiatestnet
    connections:
      - token: ethereum|holesky|0x88C916cec7c70b222cB9CB774d20444CE3ce6a68
    decimals: 18
    name: Lumia Liquid Autocompounding Pirex Ether
    standard: EvmHypSynthetic
    symbol: llapxETH
