domainRoutingIsmFactory: "0x7841cca21464F05C59Ac79D23C0855f4c308B561"
interchainAccountIsm: "0x0f3EcC1a6a8960fFF406E8ced459CC7C2C21BF54"
interchainAccountRouter: "0xAad72927CE1cF3994A8389be014F82Ce857E1352"
mailbox: "0xCE6babAFd498E0f225D0C3cABD18cbC5210D8D94"
merkleTreeHook: "0xBba6eF00EBE301508b987334f3a68f05C023Dc7B"
proxyAdmin: "0xCaA1Dd9CC0bdd05F6919C3F2BaA81fcc15D069DE"
staticAggregationHookFactory: "0x6EF866091F2cee3A58279AF877C2266498c95D31"
staticAggregationIsmFactory: "0x0C836e32c8eA3009d4CA63e5D336C52432bBcc8e"
staticMerkleRootMultisigIsmFactory: "0x179C1c60B5af23b765E263f0D5F758239CF1EE32"
staticMerkleRootWeightedMultisigIsmFactory: "0x639c56204E502626F855edC2993b6579d0eE46dE"
staticMessageIdMultisigIsmFactory: "0xde53c05e25328C1Ac90d9d1dE57291171361ba76"
staticMessageIdWeightedMultisigIsmFactory: "0xFeA618E29263A0501533fd438FD33618139F6E7b"
testRecipient: "0xd75495c8805c982a8E461dBac7711546bc1BE547"
validatorAnnounce: "0xd3F24D12414BbA7D244182bDfc4Cc75165C0A387"
