defaultHook:
  type: merkleTreeHook
defaultIsm:
  relayer: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
  type: trustedRelayerIsm
owner: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
proxyAdmin:
  owner: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
requiredHook:
  beneficiary: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
  maxProtocolFee: "100000000000000000"
  owner: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
  protocolFee: "0"
  type: protocolFee
