holesky:
  interchainSecurityModule:
    modules:
      - relayer: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
        type: trustedRelayerIsm
      - domains: {}
        owner: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
        type: defaultFallbackRoutingIsm
    threshold: 1
    type: staticAggregationIsm
  isNft: false
  mailbox: "0x46f7C5D896bbeC89bE1B19e4485e59b4Be49e9Cc"
  owner: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
  proxyAdmin:
    address: "0x33dB966328Ea213b0f76eF96CA368AB37779F065"
    owner: "0xfaD1C94469700833717Fa8a3017278BC1cA8031C"
  token: "0x5899C38154D4fa25661C6026CbE8305E0d9AEDfE"
  type: collateral
lumiatestnet:
  interchainSecurityModule:
    modules:
      - relayer: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
        type: trustedRelayerIsm
      - domains: {}
        owner: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
        type: defaultFallbackRoutingIsm
    threshold: 1
    type: staticAggregationIsm
  isNft: false
  mailbox: "0xCE6babAFd498E0f225D0C3cABD18cbC5210D8D94"
  owner: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
  proxyAdmin:
    address: "0xCaA1Dd9CC0bdd05F6919C3F2BaA81fcc15D069DE"
    owner: "0xf48A66519fAeF46E06dA57ed6d7235bBaB2a4780"
  type: synthetic

